# -*- coding: utf-8 -*-
"""bitstring_part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EniT9MD8zSUyUfnKHPv3uD6LYB5ojLUB
"""

from typing import List, Iterator, Tuple, Iterable
from dataclasses import dataclass

def occupied_indices(det: int) -> List[int]:
    occ = []
    x = det
    while x:
        lsb = x & -x
        occ.append(lsb.bit_length() - 1)
        x &= x - 1
    return occ

def virtual_indices(det: int, n_orb: int) -> List[int]:
    mask = (1 << n_orb) - 1
    vir_bits = (~det) & mask
    return occupied_indices(vir_bits)

def single_dets(det: int, n_orb: int):
    occs = occupied_indices(det)
    virs = virtual_indices(det, n_orb)
    for i in occs:
        bi = 1 << i
        for a in virs:
            yield det ^ bi ^ (1 << a)

def double_dets(det: int, n_orb: int):
    occs = occupied_indices(det)
    virs = virtual_indices(det, n_orb)
    occ_bits = [1 << i for i in occs]
    vir_bits = [1 << a for a in virs]
    for ii in range(len(occs)):
        bi = occ_bits[ii]
        for jj in range(ii + 1, len(occs)):
            bij = bi ^ occ_bits[jj]
            for aa in range(len(virs)):
                ba = vir_bits[aa]
                for bb in range(aa + 1, len(virs)):
                    yield det ^ bij ^ ba ^ vir_bits[bb]

def iter_set_bits(x: int) -> Iterator[int]:
    while x:
        lsb = x & -x
        yield lsb.bit_length() - 1
        x &= x - 1

@dataclass(frozen=True)
class SpinInterleavedPrecomp:
    n_orb: int                 # total interleaved orbitals (bits 0..n_orb-1)
    n_up: int                  # number of even orbitals
    n_dn: int                  # number of odd orbitals
    mask_all: int
    mask_even: int
    mask_odd: int
    up_full: int               # (1<<n_up)-1
    dn_full: int               # (1<<n_dn)-1
    even_bit: Tuple[int, ...]  # even_bit[k] = 1<<(2k)
    odd_bit: Tuple[int, ...]   # odd_bit[k]  = 1<<(2k+1)

def make_precomp(n_orb: int) -> SpinInterleavedPrecomp:
    # count evens/odds within 0..n_orb-1
    n_up = (n_orb + 1) // 2
    n_dn = n_orb // 2

    mask_all = (1 << n_orb) - 1

    # even mask via 0x55.. pattern, then clip to n_orb bits
    base_even = int('5' * ((n_orb + 3) // 4), 16)
    mask_even = base_even & mask_all
    mask_odd = mask_all ^ mask_even

    even_bit = tuple(1 << (2 * k) for k in range(n_up))
    odd_bit  = tuple(1 << (2 * k + 1) for k in range(n_dn))

    return SpinInterleavedPrecomp(
        n_orb=n_orb,
        n_up=n_up,
        n_dn=n_dn,
        mask_all=mask_all,
        mask_even=mask_even,
        mask_odd=mask_odd,
        up_full=(1 << n_up) - 1,
        dn_full=(1 << n_dn) - 1,
        even_bit=even_bit,
        odd_bit=odd_bit
    )

def compact_lists_from_interleaved(det: int, pc: SpinInterleavedPrecomp):
    """
    From interleaved det -> lists of compact occupied/virtual indices for up and down.
    Compact index k corresponds to interleaved:
      up: p = 2k
      dn: p = 2k+1
    Returns: (occ_up, vir_up, occ_dn, vir_dn)
    """
    d = det & pc.mask_all

    # occupied even/odd positions in interleaved indexing
    occ_even_pos = d & pc.mask_even
    occ_odd_pos  = d & pc.mask_odd

    # build compact occupation bitstrings by iterating occupied positions
    occ_up_comp = 0
    for p in iter_set_bits(occ_even_pos):
        occ_up_comp |= 1 << (p >> 1)

    occ_dn_comp = 0
    for p in iter_set_bits(occ_odd_pos):
        occ_dn_comp |= 1 << (p >> 1)

    # compact virtual bitstrings
    vir_up_comp = (~occ_up_comp) & pc.up_full
    vir_dn_comp = (~occ_dn_comp) & pc.dn_full

    # lists (compact indices)
    occ_up = list(iter_set_bits(occ_up_comp))
    vir_up = list(iter_set_bits(vir_up_comp))
    occ_dn = list(iter_set_bits(occ_dn_comp))
    vir_dn = list(iter_set_bits(vir_dn_comp))

    return occ_up, vir_up, occ_dn, vir_dn

def singles_spin_conserving_fast(det: int, pc: SpinInterleavedPrecomp) -> List[int]:
    """
    All spin-conserving singles from interleaved det, returned as interleaved dets.
    up: even->even ; dn: odd->odd
    """
    d = det & pc.mask_all
    occ_up, vir_up, occ_dn, vir_dn = compact_lists_from_interleaved(d, pc)

    out: List[int] = []
    out_append = out.append

    # up singles
    even_bit = pc.even_bit
    for i in occ_up:
        bi = even_bit[i]
        for a in vir_up:
            out_append(d ^ bi ^ even_bit[a])

    # down singles
    odd_bit = pc.odd_bit
    for i in occ_dn:
        bi = odd_bit[i]
        for a in vir_dn:
            out_append(d ^ bi ^ odd_bit[a])

    return out

def doubles_spin_conserving_fast(det: int, pc: SpinInterleavedPrecomp) -> List[int]:
    d = det & pc.mask_all
    occ_up, vir_up, occ_dn, vir_dn = compact_lists_from_interleaved(d, pc)

    out: List[int] = []
    out_append = out.append

    even_bit = pc.even_bit
    odd_bit  = pc.odd_bit

    # (1) up-up -> up-up
    for ii in range(len(occ_up)):
        bi = even_bit[occ_up[ii]]
        for jj in range(ii + 1, len(occ_up)):
            bij = bi ^ even_bit[occ_up[jj]]
            for aa in range(len(vir_up)):
                ba = even_bit[vir_up[aa]]
                for bb in range(aa + 1, len(vir_up)):
                    out_append(d ^ bij ^ ba ^ even_bit[vir_up[bb]])

    # (2) dn-dn -> dn-dn
    for ii in range(len(occ_dn)):
        bi = odd_bit[occ_dn[ii]]
        for jj in range(ii + 1, len(occ_dn)):
            bij = bi ^ odd_bit[occ_dn[jj]]
            for aa in range(len(vir_dn)):
                ba = odd_bit[vir_dn[aa]]
                for bb in range(aa + 1, len(vir_dn)):
                    out_append(d ^ bij ^ ba ^ odd_bit[vir_dn[bb]])

    # (3) up-dn -> up-dn
    for i in occ_up:
        bi = even_bit[i]
        for j in occ_dn:
            bij = bi ^ odd_bit[j]
            for a in vir_up:
                ba = even_bit[a]
                for b in vir_dn:
                    out_append(d ^ bij ^ ba ^ odd_bit[b])

    return out

def bitstring_from_occupied(n_orb: int, occ_orbs: Iterable[int]) -> int:
    """
    Build bitstring det for orbitals 0..n_orb-1 given occupied orbital indices.
    """
    det = 0
    for p in occ_orbs:
        if p < 0 or p >= n_orb:
            raise ValueError(f"orbital index {p} out of range [0,{n_orb-1}]")
        det |= 1 << p
    return det

def get_exc_list_u1(x,nsite,nexs=2):
    if nexs>2:
        raise ValueError
    ls = []
    if nexs>=1:
        ls += list(single_dets(x,nsite))
    if nexs>=2:
        ls += list(double_dets(x,nsite))
    return ls
def precompute_for_exc_ls(nsite):
    return SpinInterleavedPrecomp.make_precomp(nsite)
def get_exc_list_u11(x,pc,nexs=2):
    if nexs>2:
        raise ValueError
    ls = []
    if nexs>=1:
        ls += singles_spin_conserving_fast(x,pc)
    if nexs>=2:
        ls += doubles_spin_conserving_fast(x,pc)
    return ls
def get_random_config_u1(nsite,nelec,rng,occ=None):
    if occ is None:
        occ = rng.choice(nsite,size=nelec,replace=False)
    return bitstring_from_occupied(nsite,occ)
def get_random_config_u1(nsite,nelec,rng,occ=None):
    if occ is None:
        occ = rng.choice(nsite,size=nelec,replace=False)
    return bitstring_from_occupied(nsite,occ)
def get_random_config_u11(nsites,nelecs,rng,occ=(None,None)):
    if occ[0] is None:
        occ[0] = rng.choice(nsites[0],size=nelecs[0],replace=False)
    if occ[1] is None:
        occ[1] = rng.choice(nsites[1],size=nelecs[1],replace=False)
    occ = [2*p for p in occ[0]]+[2*p+1 for p in occ[1]]
    return bitstring_from_occupied(sum(nsites),occ=occ)