# -*- coding: utf-8 -*-
"""bitstring_part3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxjiYVsxPVluRgTY0b4SdEO_tcFti06D
"""

def excite_single(x: int, i: int, a: int):
    if ((x >> i) & 1) == 0 or ((x >> a) & 1) == 1:
        return None

    if i < a:
        mask = ((1 << a) - 1) ^ ((1 << (i + 1)) - 1)
    else:
        mask = ((1 << i) - 1) ^ ((1 << (a + 1)) - 1)

    sign = -1 if ((x & mask).bit_count() & 1) else 1
    y = x ^ (1 << i) ^ (1 << a)
    return y, sign


def excite_double(x: int, i: int, j: int, a: int, b: int):
    if (i == j) or (a == b) or (i == a) or (i == b) or (j == a) or (j == b):
        return None

    if (((x >> i) & 1) == 0 or
        ((x >> j) & 1) == 0 or
        ((x >> a) & 1) == 1 or
        ((x >> b) & 1) == 1):
        return None

    sign = 1
    m = x

    if (m & ((1 << j) - 1)).bit_count() & 1:
        sign = -sign
    m ^= (1 << j)

    if (m & ((1 << i) - 1)).bit_count() & 1:
        sign = -sign
    m ^= (1 << i)

    if (m & ((1 << b) - 1)).bit_count() & 1:
        sign = -sign
    m |= (1 << b)

    if (m & ((1 << a) - 1)).bit_count() & 1:
        sign = -sign
    m |= (1 << a)

    return m, sign