# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFf4TUd4LanpPhKhQXAhrnv5r91ULUNV
"""

from typing import Optional, Tuple, Sequence, List
import numpy as np

def gosper_next(x: int) -> int:
    """
    Return next higher integer with same number of 1-bits.
    If overflow (no next within the same bit-length), result will exceed limit.
    """
    c = x & -x
    r = x + c
    return (((r ^ x) >> 2) // c) | r

def all_dets_bitwise(n_orb: int, n_e: int):
    """
    Yield all determinants (bitstrings) with exactly n_e electrons
    in n_orb orbitals, as Python ints.
    """
    if n_e < 0 or n_e > n_orb:
        return
    if n_e == 0:
        yield 0
        return

    x = (1 << n_e) - 1              # e.g. 000111
    limit = 1 << n_orb              # stop when we exceed n_orb bits

    while x < limit:
        yield x
        x = gosper_next(x)

def interleave_up_bits(x: int) -> int:
    """
    Map compact up bitstring x (bit i = site i) to global determinant bits (2*i).
    """
    det = 0
    while x:
        lsb = x & -x
        i = lsb.bit_length() - 1
        det |= 1 << (2*i)
        x ^= lsb
    return det

def interleave_dn_bits(y: int) -> int:
    """
    Map compact down bitstring y (bit j = site j) to global determinant bits (2*j+1).
    """
    det = 0
    while y:
        lsb = y & -y
        j = lsb.bit_length() - 1
        det |= 1 << (2*j + 1)
        y ^= lsb
    return det

def configs_interleaved_spin_fast(
    n_up_sites: int,
    n_dn_sites: int,
    n_up_e: int,
    n_dn_e: int
):
    if n_up_e < 0 or n_up_e > n_up_sites:
        return
    if n_dn_e < 0 or n_dn_e > n_dn_sites:
        return

    # compact bitstrings (length n_up_sites / n_dn_sites)
    if n_up_e == 0:
        up_list = [0]
    else:
        x = (1 << n_up_e) - 1
        limit = 1 << n_up_sites
        up_list = []
        while x < limit:
            up_list.append(x)
            x = gosper_next(x)

    if n_dn_e == 0:
        dn_list = [0]
    else:
        y = (1 << n_dn_e) - 1
        limit = 1 << n_dn_sites
        dn_list = []
        while y < limit:
            dn_list.append(y)
            y = gosper_next(y)

    for x in up_list:
        det_up = interleave_up_bits(x)
        for y in dn_list:
            det_dn = interleave_dn_bits(y)
            yield det_up | det_dn

def apply_creation(det: int, p: int) -> Tuple[Optional[int], int]:
    """
    Apply fermionic creation operator c_p^† to |det>.
    Returns (new_det, sign). If result is zero, returns (None, 0).
    """
    # already occupied -> zero
    if (det >> p) & 1:
        return None, 0

    # number of occupied orbitals with index < p
    left_mask = (1 << p) - 1
    n_left = (det & left_mask).bit_count()
    sign = -1 if (n_left & 1) else +1

    new_det = det | (1 << p)
    return new_det, sign


def apply_annihilation(det: int, p: int) -> Tuple[Optional[int], int]:
    """
    Apply fermionic annihilation operator c_p to |det>.
    Returns (new_det, sign). If result is zero, returns (None, 0).
    """
    # unoccupied -> zero
    if ((det >> p) & 1) == 0:
        return None, 0

    left_mask = (1 << p) - 1
    n_left = (det & left_mask).bit_count()
    sign = -1 if (n_left & 1) else +1

    new_det = det & ~(1 << p)
    return new_det, sign

def count_up_dn(det: int, n_sites: int) -> Tuple[int, int, int]:
    """
    Count electrons in an interleaved bitstring det with 2*n_sites bits:
      up  at bit 2*i
      down at bit 2*i+1

    Returns (N_total, N_up, N_dn).
    """
    # Mask selecting all even bits in the first 2*n_sites positions: 010101...
    even_mask = 0
    for i in range(n_sites):
        even_mask |= 1 << (2*i)

    up = (det & even_mask).bit_count()
    total = (det & ((1 << (2*n_sites)) - 1)).bit_count()
    dn = total - up
    return total, up, dn

def masks_from_ctr_ls(ctr_ls: Sequence[Sequence[int]]) -> List[int]:
    """Precompute bitmasks for each rs in ctr_ls."""
    masks = []
    for rs in ctr_ls:
        m = 0
        for r in rs:
            m |= (1 << r)
        masks.append(m)
    return masks
def compute_occ_bits_from_masks(det: int, masks: Sequence[int]) -> np.ndarray:
    """
    Returns a NumPy array of 0/1 for each mask:
      out[i] = 1 iff (det & masks[i]) == masks[i]
    """
    out = np.empty(len(masks), dtype=np.int8)
    for i, m in enumerate(masks):
        out[i] = 1 if (det & m) == m else 0
    return out

def get_all_configs_u1(nsites,nelecs):
  return all_dets_bitwise(nsites,nelecs)
def get_all_configs_u11(nsites,nelecs):
  return configs_interleaved_spin_fast(nsites[0],nsites[1],nelecs[0],nelecs[1])
def fermion_act(x,oix,typ):
  if typ=='cre':
    return apply_creation(x,oix)
  elif typ=='des':
    return apply_annihilation(x,oix)
  else:
    raise ValueError
def string_act(x,ops,order=-1):
  if order==-1:
    ops = ops[::-1]
  s = 1
  y = x
  for i,(oix,typ) in enumerate(ops):
    y,si = fermion_act(y,oix,typ)
    if y is None:
      return None,0
    s *= si
  return y,s
def check_symmetry(x,symmetry,nsite,nelec):
  N,Na,Nb = count_up_dn(x,nsite//2)
  if symmetry=='u1':
    if N!=sum(nelec):
      return False
  if symmetry=='u11':
    if Na!=nelec[0]:
      return False
    if Nb!=nelec[1]:
      return False
  return True
def ctr_ls_to_masks(ctr_ls):
  if ctr_ls is None:
    return None
  return masks_from_ctr_ls(ctr_ls)
def ctr_ls_to_occ(cf,masks):
  return compute_occ_bits_from_masks(cf,masks)